### ISSUE TITLE
Burst not supported

### ISSUE THREAD

**Issue by donitry** [cathei/LinqGen#12]
i use linqgen in job file like this:
[BurstCompile(CompileSynchronously = true)]
public struct MovementJob : IJob
{
  ......
public void Execute()
{
....
TilePath startPath = movementRange.Gen().Where(p=>p.gridPosition == startDird).FirstOrDefault();
....
movementRange.Gen().Where(p =>
{
    int __distance = AStarPathfinding.GetEstimatedPathCost(startPath.position, p.position);
    if (__distance > 0 && __distance <= _distance)
        return true;
    return false;
}).ToList().ForEach(p =>
    {
        p.adjacentTiles.ForEach(q =>
        {
            if (q.g < 0 && p.g >= 0) {  q.g = p.g + q.cost; }
        });
        //return true;
    });
}

}

unity editor Error
"The managed function `MovementJob.<>c__DisplayClass6_0.<AStarPathFinding>b__0(MovementJob.<>c__DisplayClass6_0* this, TilePath p) -> bool_eefeb7bf1a3bdcec3e8017e3deeff512 from Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null` is not supported
"
The location pointed out by the error is exactly where linqgen is used。。。。

there is something worry i miss???

**Comment by cathei** [comment]
To use LinqGen with burst you must use `IStructFunction`. Lambdas and Lists are managed type and not supported by Burst.
